### ISSUE TITLE
Make tokens jitsi-compatible

### ISSUE THREAD

**Issue by nampereira** [conix-center/arena-account#31]
Modifying tokens a little would let Jitsi accept them:
```
Header:
{
  "kid": "arena-public-key",
  "alg": "RS256",
  "typ": "JWT"
}
Body:
{ 
  "context": { 
    "user": {
      "name": "<ARENA.displayName + "#4r3n4_" + ARENA.idTag>",
       "arenaId": "<ARENA.idTag>",
       "arenaDisplayName": "<ARENA.displayName>",
        "arenaCameraName": "<ARENA.camName>" 
    }
  },
  "aud": "arena",
  "iss": "arena-account",
  "room": "<scene-name>",
  "exp": 1615233011,
  "sub": "<username>",
  "subs": [ "#" ],
  "publ": [ "#" ]
}
```

This ensures that our jitsi server is only used by arena users.

Not sure we need arenaId, arenaDisplayName, arenaCameraName, but think it does not hurt.

**Comment by nampereira** [comment]
Ah, screenshare clients need a different context.  Maybe the best is to just remove context from the body (sorry!).

Body:
```
{ 
  "aud": "arena",
  "iss": "arena-account",
  "room": "<scene-name>",
  "exp": 1615233011,
  "sub": "<username>",
  "subs": [ "#" ],
  "publ": [ "#" ]
}
```

**Comment by mwfarb** [comment]
Sure, let me know if this takes care of it: https://github.com/conix-center/arena-account/commit/1eafc8c1b47e07b73d255c03d1be5bdf3c2b7298. We can always add it back.
